- id: '1576248771931'
  alias: Shelly Plug bij sfeerhaard aan
  trigger:
  - entity_id: light.woonkamer
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: switch.shelly_plug_s_7ae6df
    service: switch.turn_on
- id: '1576249568285'
  alias: Shelly Plug bij sfeerhaard uit
  trigger:
  - entity_id: light.woonkamer
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: switch.shelly_plug_s_7ae6df
    service: switch.turn_off
- id: '1590256194941'
  alias: Waarschuwing Batterij Shelly HT Werkkamer < 60%
  trigger:
  - below: '60'
    entity_id: sensor.shelly_ht_b8954a_battery
    for:
      hours: 8
    platform: numeric_state
  condition: []
  action:
  - data:
      message: De batterij van de Shelly HT Werkkamer heeft < 60% lading.
      title: Batterij Shelly HT Werkkamer minder dan 60%
    service: notify.mobile_app_iphone_van_dennis
- id: '1590256760870'
  alias: Waarschuwing batterij iPhone Nicole minder dan 37%
  trigger:
  - below: '37'
    entity_id: sensor.battery_level_4
    for: 0:02:00
    platform: numeric_state
  condition: []
  action:
  - data:
      message: De accu van de iPhone van Nicole heeft < 37% lading.
      title: Accu iPhone van Nicole laag
    service: notify.mobile_app_iphone_van_dennis
- id: '1590257138342'
  alias: ' Waarschuwing Batterij Shelly HT Woonkamer < 60%'
  trigger:
  - below: '60'
    entity_id: sensor.shelly_ht_b89774_battery
    for:
      hours: 8
    platform: numeric_state
  condition: []
  action:
  - data:
      message: De batterij van de Shelly HT Woonkamer heeft < 60% lading.
      title: Batterij Shelly HT Woonkamer minder dan 60%
    service: notify.mobile_app_iphone_van_dennis
- id: '1590257621165'
  alias: Waarschuwing batterij Hue Dimmer Woonkamer < 40%
  trigger:
  - below: '40'
    entity_id: sensor.dimmer_woonkamer_battery_level
    for:
      hours: 1
    platform: numeric_state
  condition: []
  action:
  - data:
      message: De batterij van de Hue Dimmer Woonkamer heeft < 40% lading.
      title: Batterij Hue Dimmer Woonkamer minder dan 40%
    service: notify.mobile_app_iphone_van_dennis
- id: '1590257764955'
  alias: Waarschuwing batterij Hue Dimmer Werkkamer < 40%
  trigger:
  - below: '40'
    entity_id: sensor.dimmer_eetkamer_battery_level
    for:
      hours: 1
    platform: numeric_state
  condition: []
  action:
  - data:
      message: De batterij van de Hue Dimmer Werkkamer heeft < 40% lading.
      title: Batterij Hue Dimmer Werkkamer minder dan 40%
    service: notify.mobile_app_iphone_van_dennis
- id: '1591347283396'
  alias: Bericht sturen als het op de werkkamer warmer is dan in de woonkamer
  trigger:
    platform: template
    value_template: '{{ states(''sensor.shelly_ht_b8954a_temperature'') | float >
      states(''sensor.shelly_ht_b89774_temperature'') | float }}'
  action:
  - data:
      message: Het is nu op de werkkamer {{ states.sensor.shelly_ht_b8954a_temperature.state
        }} graden, in de woonkamer is het nu {{ states.sensor.shelly_ht_b89774_temperature.state
        }} graden.
      title: Werkkamer warmer dan woonkamer!
    service: notify.mobile_app_iphone_van_dennis
- id: '1620134867197'
  alias: Xiaomi testen
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      motion_entity: binary_sensor.0x00158d00051ddcff_occupancy
      light_target:
        entity_id: light.hue_ambiance_panel_1
      no_motion_wait: 60
- id: '1627288358318'
  alias: Buiten warmer dan werkkamer
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.openweathermap_temperature'') | float > states(''sensor.shelly_ht_b8954a_temperature'')
      | float }}'
  condition: []
  action:
  - service: notify.mobile_app_iphone_van_dennis
    data:
      title: Buiten warmer dan op de werkkamer!
      message: Het is nu op de werkkamer {{ states.sensor.shelly_ht_b8954a_temperature.state
        }} graden, buiten is het {{ states.sensor.openweathermap_temperature.state
        }} graden.
  mode: single
- id: '1627288708834'
  alias: Buiten warmer dan woonkamer
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.openweathermap_temperature'') | float > states(''sensor.shelly_ht_b89774_temperature'')
      | float }}'
  condition: []
  action:
  - service: notify.mobile_app_iphone_van_dennis
    data:
      title: Buiten warmer dan woonkamer!
      message: Het is nu in de woonkamer {{ states.sensor.shelly_ht_b89774_temperature.state
        }} graden, buiten is het {{ states.sensor.openweathermap_temperature.state
        }} graden.
  mode: single
- id: '1636216284999'
  alias: Buitenverlichting terras aan bij zonsondergang
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.shelly_1pm_e67b86
  mode: single
- id: '1636216499389'
  alias: Buitenverlichting terras uit bij zonsopkomst
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.shelly_1pm_e67b86
  mode: single
- id: '1639747382064'
  alias: Waarschuwing battery Aqara bewegingsensor < 60%
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.0x00158d00051ddcff_battery
    below: '60'
    for:
      hours: 8
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: notify.mobile_app_iphone_van_dennis
    data:
      message: De batterij van de Aqara bewegingsensor heeft < 60% lading.
      title: Batterij Aqara bewegingsensor minder dan 60%
  mode: single
- id: '1639747538163'
  alias: Waarschuwing batterij Aqara klimaatsensor werkkamer < 60%
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.0x00158d0007df9809_battery
    below: '60'
    for:
      hours: 8
      minutes: 0
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: notify.mobile_app_iphone_van_dennis
    data:
      message: De batterij van de Aqara klimaatsensor op de werkkamer heeft < 60%
        lading.
      title: Batterij klimaatsensor werkkamer minder dan 60%
  mode: single
