homeassistant:
  # Name of the location where Home Assistant is running
  #  name: !secret homeassistant_location_name
  # Location required to calculate the time the sun rises and sets
  #  latitude: !secret zone_home_latitude
  #  longitude: !secret zone_home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  #  elevation: !secret zone_home_elevation
  # metric for Metric, imperial for Imperial
  #  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  #  time_zone: !secret timezone
  # Customization file
  customize: !include customize.yaml
  # URL's
  external_url: !secret external_url
  internal_url: !secret internal_url

  packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  ip_ban_enabled: true
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.19.0.0/16
  login_attempts_threshold: 3

  #history: !include include/history.yaml

# Discover some devices automatically
discovery:

switch: !include include/switches.yaml
  
sensor: !include include/sensors.yaml

utility_meter: !include include/utility_meters.yaml

recorder: !include include/recorder.yaml

zwave:
  usb_path: /dev/ttyACM0

influxdb:
  host: influxdb.docker_default
  port: 8086
  database: home_assistant
  include:
    domains:
      - sensor
      - binary_sensor
  exclude:
    domains:
      - zone
      - sun
      - light
      - group
      - person
      - device_tracker

# People
#person: !include include/persons.yaml

# Zones
zone: !include include/zones.yaml

ios:

# Weather
#weather:
#  - platform: buienradar
#    name: 'Lokaal weer'
#    forecast: true

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

mqtt:
  broker: mosquitto.docker_default
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'

    #media_player: !include include/media_player.yaml

